# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dv7ZKVB3ojEBGD2QjmY7t_VSYuV6uF8F
"""

import cv2
import matplotlib.pyplot as plt

def rasmni_korish_va_kulrangga_ozgartirish(rasm_nomi):
    rasm = cv2.imread(rasm_nomi)

    if rasm is not None:
        rasm = cv2.cvtColor(rasm, cv2.COLOR_BGR2RGB)

        oqqora = cv2.cvtColor(cv2.imread(rasm_nomi), cv2.COLOR_BGR2GRAY)

        fig, axs = plt.subplots(1, 2, figsize=(12, 6))
        axs[0].imshow(rasm)
        axs[0].set_title(f"Asl rasm: {rasm_nomi}")
        axs[0].axis('off')

        axs[1].imshow(oqqora, cmap='gray')
        axs[1].set_title(f"Grayscale rasm: {rasm_nomi}")
        axs[1].axis('off')

        plt.show()
    else:
        print(f"Rasmni o'qishda xato: {rasm_nomi} mavjud emas!")

rasmlar = ["2 rasim menga keregi.jpg", "i.webp", "Winter11.jpg", "Winter12.jpg", "1111111.jpg", "5018.jpg"]

for rasm_nomi in rasmlar:
    rasmni_korish_va_kulrangga_ozgartirish(rasm_nomi)